### ISSUE TITLE
Footer UI Fixes

### ISSUE THREAD

**Issue by Sahaj-IBM** [ibm-client-engineering/ce-solutions-hub#52]
- Footer floats sometimes, it needs to be stuck to bottom
- The language/location setting should not open or be clickable. It should always be locked and set to United States - English
- 
![Screenshot 2024-05-30 at 1 39 49 PM](https://github.com/ibm-client-engineering/ce-solutions-hub/assets/139918147/ade89382-1aae-464e-b7a1-286dd7a6511e)

**Comment by SamLee-IBM** [comment]
resolved by #71
