### ISSUE TITLE
Implement filtering with search on projects page

### ISSUE THREAD

**Issue by Sahaj-IBM** [ibm-client-engineering/ce-solutions-hub#54]
- Currently the app has a basic search that looks for matches in name and description.
- We need to implement a search that allows you to filter projects by tags, patterns (gen ai, data, aiops, etc.), and other fields

![Screenshot 2024-05-30 at 1 47 39 PM](https://github.com/ibm-client-engineering/ce-solutions-hub/assets/139918147/2697739b-1856-4b4a-b092-6f2cfa84fadd)

**Comment by SamLee-IBM** [comment]
Filtering works, but there is another issue with the multiselect component, where selecting an item selects it twice, leading to odd behavior and a double incremented tag count.

<img width="1502" alt="Screenshot 2024-06-06 at 11 53 57 AM" src="https://github.com/ibm-client-engineering/ce-solutions-hub/assets/158353838/9adaec12-6c31-4a95-841e-cdfb0cc7875b">
