### ISSUE TITLE
Fix the promo cards on the Home Page 

### ISSUE THREAD

**Issue by angelawa109** [ibm-client-engineering/ce-solutions-hub#88]
Please fix the promo cards to align with the color boxes on the top. I used "Card Default" from Carbon for the Figma design. 
![Screenshot 2024-06-27 at 12 41 56 PM](https://github.com/ibm-client-engineering/ce-solutions-hub/assets/173483934/d4020e14-48e8-4abd-90c0-6fb3b77c796d)

**Comment by Sahaj-IBM** [comment]
@SamLee-IBM I believe the goal is to get the styling of recent and popular projects to line up with the top boxes better

**Comment by SamLee-IBM** [comment]
I will try left, center, right aligned

**Comment by Sahaj-IBM** [comment]
https://github.com/ibm-client-engineering/ce-solutions-hub/pull/92
